import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShieldCheck, Smartphone, Code2, Sparkles } from 'lucide-react';
export const Navbar = ({ currentView, onSelectView, sessions, onOpenNewSession, onOpenNewBroadcast }) => {
    const connectedCount = sessions.filter(s => s.status === 'CONNECTED').length;
    return (_jsx("header", { className: "bg-[#111b21] border-b border-[#2a3942] sticky top-0 z-40 px-4 py-2.5", children: _jsxs("div", { className: "max-w-7xl mx-auto flex items-center justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-tr from-emerald-600 to-teal-500 shadow-lg shadow-emerald-900/30 text-white", children: _jsx(Smartphone, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-extrabold text-lg tracking-tight bg-gradient-to-r from-white via-slate-200 to-emerald-400 bg-clip-text text-transparent", children: "WppFlow" }), _jsx("span", { className: "text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-emerald-950/80 text-emerald-400 border border-emerald-800/60", children: "10x Interakt" })] }), _jsxs("p", { className: "text-[11px] text-slate-400 font-medium", children: ["Powered by ", _jsx("span", { className: "text-emerald-400 font-semibold", children: "WPPConnect" }), " \u2022 $0 Meta Conversation Fees"] })] })] }), _jsxs("div", { className: "hidden md:flex items-center bg-[#202c33] p-1 rounded-xl border border-[#2a3942]", children: [_jsxs("button", { onClick: () => onSelectView('user'), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${currentView === 'user'
                                ? 'bg-emerald-600 text-white shadow-md'
                                : 'text-slate-400 hover:text-slate-200 hover:bg-[#111b21]'}`, children: [_jsx(Smartphone, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "User Workspace" })] }), _jsxs("button", { onClick: () => onSelectView('admin'), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${currentView === 'admin'
                                ? 'bg-indigo-600 text-white shadow-md'
                                : 'text-slate-400 hover:text-slate-200 hover:bg-[#111b21]'}`, children: [_jsx(ShieldCheck, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Super Admin" }), _jsx("span", { className: "bg-indigo-500/30 text-indigo-300 text-[10px] px-1.5 py-0.2 rounded font-mono", children: "Admin" })] }), _jsxs("button", { onClick: () => onSelectView('developer'), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${currentView === 'developer'
                                ? 'bg-amber-600 text-white shadow-md'
                                : 'text-slate-400 hover:text-slate-200 hover:bg-[#111b21]'}`, children: [_jsx(Code2, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Developer Guide" }), _jsx("span", { className: "bg-amber-500/30 text-amber-300 text-[10px] px-1.5 py-0.2 rounded font-mono", children: "REST / SDK" })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { onClick: onOpenNewSession, title: "Manage connected WhatsApp instances", className: "flex items-center gap-2 bg-[#202c33] border border-[#2a3942] hover:border-emerald-500/50 px-3 py-1.5 rounded-lg cursor-pointer transition-all", children: [_jsxs("span", { className: "relative flex h-2.5 w-2.5", children: [_jsx("span", { className: "animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" }), _jsx("span", { className: "relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500" })] }), _jsxs("span", { className: "text-xs font-medium text-slate-300", children: [_jsx("span", { className: "text-emerald-400 font-bold", children: connectedCount }), " Sessions Live"] })] }), _jsxs("button", { onClick: onOpenNewBroadcast, className: "hidden sm:flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold px-3 py-1.5 rounded-lg transition-all shadow-md shadow-emerald-900/20", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "New Broadcast" })] }), _jsxs("div", { className: "flex items-center gap-2 pl-2 border-l border-[#2a3942]", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=80&auto=format&fit=crop&q=80", alt: "User profile", className: "w-8 h-8 rounded-full ring-2 ring-emerald-500/30 object-cover" }), _jsxs("div", { className: "hidden lg:block text-left text-xs leading-tight", children: [_jsx("div", { className: "font-semibold text-slate-200", children: "Aarav Mehta" }), _jsx("div", { className: "text-[10px] text-emerald-400 font-medium", children: "Urban Threads (Enterprise)" })] })] })] })] }) }));
};
