import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Webhook, Sparkles, Activity } from 'lucide-react';
export const WebhookSimulator = ({ logs, onTriggerTestWebhook }) => {
    const [selectedLogId, setSelectedLogId] = useState(logs[0]?.id || '');
    const [webhookUrl, setWebhookUrl] = useState('https://api.yourbrand.com/webhooks/whatsapp');
    const [isSaved, setIsSaved] = useState(false);
    const selectedLog = logs.find(l => l.id === selectedLogId) || logs[0];
    const handleSaveUrl = (e) => {
        e.preventDefault();
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 2500);
    };
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-[#111b21] p-5 rounded-2xl border border-[#2a3942] space-y-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "p-2 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20", children: _jsx(Webhook, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-base font-bold text-white", children: "Webhook Dispatch URL" }), _jsx("p", { className: "text-xs text-slate-400", children: "Receive real-time incoming messages, status acks (sent/delivered/read), and device battery events." })] })] }), _jsxs("form", { onSubmit: handleSaveUrl, className: "flex flex-col sm:flex-row items-center gap-3 pt-1", children: [_jsx("input", { type: "url", value: webhookUrl, onChange: (e) => setWebhookUrl(e.target.value), className: "flex-1 w-full bg-[#202c33] border border-[#2a3942] rounded-xl px-4 py-2 text-xs font-mono text-emerald-400 focus:outline-none focus:border-amber-500" }), _jsx("button", { type: "submit", className: "w-full sm:w-auto px-4 py-2 bg-amber-600 hover:bg-amber-500 text-white rounded-xl text-xs font-semibold transition-all shadow-md shadow-amber-900/30 shrink-0", children: isSaved ? 'Endpoint Saved!' : 'Save Webhook URL' })] })] }), _jsxs("div", { className: "bg-[#111b21] p-5 rounded-2xl border border-[#2a3942] space-y-4", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-sm font-bold text-white flex items-center gap-2", children: [_jsx(Activity, { className: "w-4 h-4 text-emerald-400" }), _jsx("span", { children: "Real-Time Webhook Event Stream" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Inspecting outbound webhook payloads delivered to your backend" })] }), _jsxs("button", { onClick: onTriggerTestWebhook, className: "flex items-center gap-1.5 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-xl transition-all shadow-md shadow-emerald-900/30", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Trigger Mock Incoming Message" })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-4 pt-2", children: [_jsx("div", { className: "space-y-2 max-h-[400px] overflow-y-auto", children: logs.map((l) => (_jsxs("div", { onClick: () => setSelectedLogId(l.id), className: `p-3 rounded-xl border cursor-pointer transition-all ${l.id === selectedLogId
                                        ? 'bg-[#202c33] border-amber-500/50'
                                        : 'bg-[#111b21] border-[#2a3942] hover:bg-[#202c33]/40'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "font-mono text-xs font-bold text-amber-400", children: ["event: ", l.event] }), _jsx("span", { className: "text-[10px] px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-400 border border-emerald-800 font-bold uppercase", children: "200 OK" })] }), _jsx("span", { className: "text-[10px] text-slate-400 font-mono", children: l.timestamp })] }), _jsxs("div", { className: "text-[11px] text-slate-400 mt-1 font-mono", children: ["session: ", _jsx("span", { className: "text-white", children: l.session })] })] }, l.id))) }), selectedLog && (_jsxs("div", { className: "bg-[#0b141a] border border-[#2a3942] rounded-xl p-4 space-y-2 flex flex-col justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between text-xs pb-2 border-b border-[#2a3942]", children: [_jsx("span", { className: "font-semibold text-slate-300", children: "HTTP POST Payload" }), _jsx("span", { className: "font-mono text-[10px] text-emerald-400", children: "X-WPP-Signature: sha256=..." })] }), _jsx("pre", { className: "font-mono text-xs text-amber-300 overflow-x-auto mt-3 max-h-[300px]", children: JSON.stringify(selectedLog.payload, null, 2) })] }), _jsxs("div", { className: "text-[10px] text-slate-500 pt-2 border-t border-[#2a3942]", children: ["Delivery status: delivered in 42ms to ", webhookUrl] })] }))] })] })] }));
};
